# -*- coding: utf-8 -*-
"""HashTable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMeVaqJT2A9C-CW4GiuDfjZcdt_76Mgs
"""

import pandas as pd
data=pd.read_csv("/content/student_exam_scores.csv")

data

column_array = data['sleep_hours'].to_numpy()

print(data["exam_score"])

"""To find sum and avg of the columns sleep_hours"""

total = 0  # Initialize!
for i in range(len(column_array)):
    total += column_array[i]
    avg=total/len(column_array)
print("Sum of Total sleep of all Students:",total)
print("Average of Total sleep of all Students:",avg)

"""To get max

"""

max_val = max(column_array)  # or col_array.max() for numpy
print(max_val)

"""Without using function"""

largest = float('-inf')  # Start low
for value in column_array:
    if value > largest:
        largest = value
print(largest)